module.exports.descriptors = [
    'Himalayan',
    'Ancient',
    'Sacred',
    'Roaring',
    'Misty',
    'Golden',
    'Silent',
    'Banyan',
    'Monsoon',
    'Mango',
    'Emerald',
    'Royal',
    'Tiger',
    'Coastal',
    'Backwater',
    'Sunlit',
    'Dusty',
    'Sapphire'
]
module.exports.places = [
    'Valley',
    'Village',
    'Ghat',
    'Fort',
    'Base Camp',
    'Trek Camp',
    'Hill Station',
    'Camp',
    'Forest Camp',
    'Wilderness',
    'River',
    'Creek',
    'Riverside',
    'Bay',
    'Spring',
    'Lakeshore',
    'Dunes',
    'Jungle Camp',
    'Wildlife Camp',
    'Cliffs',
    'Meadow'
]